#!/usr/bin/env python
# $Id$
# 
# Copyright (2014) David Seidel.
# 
# Hermes is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
# 
# Hermes is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General
# Public License along with Hermes.  If not, see
# <http://www.gnu.org/licenses/>.
# 
# This script finds all the modules, packages, and extension modules in the
# Hermes Python directory tree constructs "make" dependencies for generating
# HTML documentation
#

import os,sys,re

maj_ver = sys.version_info[0]
if maj_ver < 3:
    from PortabilityTools2_5 import ptPrint, pathWalk
else:
    from PortabilityTools import ptPrint, pathWalk

def mywalk(arg,dname,names):
    global TargList
    global StartPath
    global HDir
    out = arg[0] ; mode = arg[1]
    ist = len(StartPath.split(os.sep))
    ##ptPrint('skip: ',ist)
    if mode == 'packages':
        try:
            loc = names.index('__init__.py')
            src = os.path.join(dname,'__init__.py')
            dsplt = dname.split(os.sep)
            module = '.'.join(dsplt[ist:])
            targ =  os.path.join(HDir, module + '.html')
            ptPrint(targ + " : " + src,file=out)
            ptPrint("\t$(PYDOC_HU) %s %s %s" % (src,module,targ),file=out)
            TargList.append(targ)
        except ValueError:
            ##ptPrint(dname, 'fail')
            pass
        return

    if mode == 'modules':
        reg = re.compile('\.py$')
    else:
        reg = re.compile('\.'+mode+'$')
        mode = 'extensions'
        ##ptPrint('xxx',reg)

    for f in names:
        if mode == 'modules' and f == '__init__.py': continue
        if reg.search(f) is not None:
            dsplt = dname.split(os.sep)
            src = os.path.join(dname,f)
            dsplt = os.path.splitext(src)[0].split(os.sep)
            if mode == 'extensions':
                fsp = f.split('.')
                if len(fsp) > 2:
                    f = '.'.join([fsp[0],fsp[-1]])
            ##ptPrint(ist,dsplt)
            if mode == 'extensions':
                module = fsp[0]
            else:
                module = '.'.join(dsplt[ist:])
            targ =  os.path.join(HDir, module + '.html')
            ptPrint(targ + " : " + src,file=out)
            ptPrint("\t$(PYDOC_HU) %s %s %s" % (src,module,targ),file=out)
            TargList.append(targ)

import chkversion

usage = '''usage: htmldeps sys_type [htmldir="../html" ] [share_ext="so"]
       [macfile=sys.stdout] [depfile=macfile]'''

##sys_type = 'linux_x86_64_intel-2.7'
shr_ext = 'so'
mout,dout = (sys.stdout,sys.stdout) 
HDirBase = '../html'
argc = len(sys.argv)
if argc == 6 and sys.argv[5] != '-':
   if sys.argv[4] != '-': mout = open(sys.argv[4],'w')
   dout = open(sys.argv[5],'w')
if argc == 5 and sys.argv[4] != '-':
   mout = open(sys.argv[4],'w')
   dout = mout
if argc >= 4:   shr_ext = sys.argv[3]
if argc >= 3:   HDir = sys.argv[2]
if argc < 2 or argc > 6:
    ptPrint(usage)
    sys.exit(1)

sys_type = sys.argv[1]

ver25exe, ver2exe, ver3exe = chkversion.getPythonExecutables()

hDirlist = []
if ver2exe is not None or ver3exe is not None: hDirlist.append(HDirBase)
if ver25exe is not None:
    if len(hDirlist) == 0: hDirlist.append(HDirBase)
    else:                  hDirlist.append(HDirBase + '2.5')

###ptPrint(ver25exe,ver2exe,ver3exe,hDirlist)

###ptPrint('args:',sys_type,HDirBase, shr_ext, mout, dout)
TargList = []

for HDir in hDirlist:
    StartPath = '../modules'
    if HDir[-3:] == '2.5': StartPath += '2.5'
    pathWalk(StartPath,mywalk,(dout,'modules'))

    pathWalk(StartPath,mywalk,(dout,'packages'))

    StartPath = '../extensions/'+sys_type
    pathWalk(StartPath,mywalk,(dout,shr_ext))


    if not os.path.exists(HDir):
        os.mkdir(HDir)

ptPrint("TARGETS = " + ' '.join(TargList),file=mout)
