#!/usr/bin/env python
# $Id$
# 
# Copyright (2014) David Seidel.
# 
# Hermes is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
# 
# Hermes is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General
# Public License along with Hermes.  If not, see
# <http://www.gnu.org/licenses/>.
# 
# This script finds all the modules, packages, and extension modules in the
# Hermes Python directory tree constructs "make" dependencies for generating
# HTML documentation
#

V2_files = ':PortabilityTools2_5.py:'
V25_dirs = [ 'modules2.5' ]

import sys,os
import chkversion

vi = list(sys.version_info)
py_ver = vi[2] + 100*(vi[1] +100*vi[0])
maj_ver = sys.version_info[0]
if maj_ver < 3:
    from PortabilityTools2_5 import ptPrint
else:
    from PortabilityTools import ptPrint

ver25exe, ver2exe, ver3exe = chkversion.getPythonExecutables()

if ver3exe is not None:
    defexe = ver3exe
else:
    defexe = ver2exe
##ptPrint(sys.version_info)
##ptPrint(ver25exe,ver2exe,ver3exe,defexe)

base = os.path.basename(sys.argv[1])

exe = None
arg3 = ''
##ptPrint('base:',base)
if V2_files.find(':'+base+':') >= 0:
    ##ptPrint('found',base)
    if ver2exe is not None: exe = ver2exe
    elif ver25exe is not None: exe = ver25exe
    else: sys.exit(0)
else:
    for dirname in V25_dirs:
        ##ptPrint(sys.argv[1],sys.argv[1].find(os.path.sep+dirname+os.path.sep))
        if sys.argv[1].find(os.path.sep+dirname+os.path.sep) >= 0:
            ##ptPrint('found',dirname)
            if ver25exe is None:
                ##ptPrint('NONE:',ver25exe)
                sys.exit(0)
            exe = ver25exe
            arg3 = ' v2.5'
            ##ptPrint('found v2.5 for',sys.argv[1])
    if exe is None: exe = ver3exe

##ptPrint('xxx',os.path.dirname(sys.argv[0]))

full_py = os.path.join(os.path.dirname(sys.argv[0]),'pydoc_HU.py' )

cmd = exe + ' ' + full_py + ' ' + ' '.join(sys.argv[2:]) + arg3
##ptPrint('cmd:',cmd)
os.system(cmd)

                                
